# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - generated

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/Brean-dev/Erebus

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
      - unnamedResult

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  misspell:
    locale: US
    ignore-words:
      - erebus

  lll:
    line-length: 120
    tab-width: 4

  unused:
    go: "1.25"

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  goconst:
    min-len: 3
    min-occurrences: 3

  godot:
    scope: declarations
    capital: true

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
      - name: package-comments
      - name: indent-error-flow
      - name: error-return
      - name: error-naming
      - name: error-strings
      - name: receiver-naming
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: context-as-argument
      - name: dot-imports
      - name: blank-imports
      - name: early-return

  gosec:
    excludes:
      - G404
    severity: medium
    confidence: medium

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
    - gosec
    - gocyclo
    - dupl
    - goconst
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - godot
    - nilerr
    - errorlint
    - bodyclose
    - noctx

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - funlen

    # Exclude specific gosec rules that are often false positives
    - linters:
        - gosec
      text: "G404:"

    # Allow errors to not be checked in main/cmd
    - path: (cmd|main)\.go
      linters:
        - errcheck
      text: "Error return value of .*(Close|Log|Print)"

    # Ignore long lines in Go directives
    - linters:
        - lll
      source: "^//go:"

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
  show-stats: false
